name: ToDoSimple

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_16.0.app
        sudo xcodebuild -license accept
    - name: Build iOS app with Xcode
      run: |
        xcodebuild clean build -workspace YourProject.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release | tee result.log
